# Generated by Django 4.1 on 2022-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
