# Generated by Django 4.1 on 2022-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_usermember_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='c_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
