# Generated by Django 4.1 on 2022-09-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0005_remove_category_subcat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
