# Generated by Django 4.1 on 2022-09-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0011_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart1',
        ),
    ]
