# Generated by Django 4.1 on 2022-09-07 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomApp', '0012_rename_cart_cart1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='usermember',
        ),
        migrations.AddField(
            model_name='cart1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
