# Generated by Django 4.1 on 2022-09-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0003_usermember_c_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product/'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile/'),
        ),
    ]
