# Generated by Django 4.1 on 2022-09-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0004_product_image_alter_usermember_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcat_name',
        ),
    ]
