# Generated by Django 4.1 on 2022-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0009_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
